### PR TITLE
Read chip silicon revision and add IO memory on chips with PDI and UPDI

### LINKED ISSUE #1472: Read silicon revision from "modern" AVRs
It seems like Pymcuprog can read a byte from (an undocumented?) memory section that can be used to determine which silicon revision the chip is. If you're struggling with a weird bug in the MCU program, it _might_ actually be a silicon bug. Being able to use Avrdude to read this revision number/letter would only be a good thing.

From [pymcuprog/serialupdi/application.py](
https://github.com/microchip-pic-avr-tools/pymcuprog/blob/593afdc8e089e39a4fed9f4fb19ae81f5f51e9a5/pymcuprog/serialupdi/application.py#L89-L145)

```py
def read_device_info(self):
        """
        Reads out device information from various sources
        """
        sib = self.readwrite.read_sib()
        sib_info = decode_sib(sib)

        # Unable to read SIB?
        if sib_info is None:
            self.logger.warning("Unable to read SIB from device; attempting double-break recovery...")
            # Send double break and try again
            self.phy.send_double_break()
            sib = self.readwrite.read_sib()
            sib_info = decode_sib(sib)
            if sib_info is None:
                self.logger.error("Double-break recovery failed.  Unable to contact device.")
                raise PymcuprogError("Failed to read device info.")

        # Select correct NVM driver:
        # P:0 = tiny0, mega0 (16-bit, page oriented)
        # P:1 = N/A
        # P:2 = AVR DA, DB, DD (24-bit, word-oriented)
        # P:3 = AVR EA (16-bit, page oriented)
        if sib_info['NVM'] == '0':
            self.logger.info("NVM type 0: 16-bit, page oriented write")
            # DL is correctly configured already
            # Create new NVM driver
            self.nvm = NvmUpdiV0(self.readwrite, self.device)
        elif sib_info['NVM'] == '2':
            # This is a Dx-family member, and needs new DL and NVM
            self.logger.info("NVM type 2: 24-bit, word oriented write")
            # Create new DL
            datalink = UpdiDatalink24bit()
            # Use the existing PHY
            datalink.set_physical(self.phy)
            # And re-init
            datalink.init_datalink()
            # Create a read write access layer using this data link
            self.readwrite = UpdiReadWrite(datalink)
            # Create new NVM driver
            self.nvm = NvmUpdiAvrV2(self.readwrite, self.device)
        elif sib_info['NVM'] == '3':
            self.logger.info("NVM type 3: 16-bit, page oriented")
            # DL is correctly configured already
            # Create new NVM driver
            self.nvm = NvmUpdiAvrV3(self.readwrite, self.device)
        else:
            self.logger.error("Unsupported NVM revision - update pymcuprog.")

        self.logger.info("PDI revision = 0x%02X", self.readwrite.read_cs(constants.UPDI_CS_STATUSA) >> 4)
        if self.in_prog_mode():
            if self.device is not None:
                devid = self.read_data(self.device.sigrow_address, 3)
                devrev = self.read_data(self.device.syscfg_address + 1, 1)
                self.logger.info("Device ID from serialupdi = '%02X%02X%02X' rev '%s'", devid[0], devid[1], devid[2],
                                 chr(ord('A') + devrev[0]))
        return sib_info
```

### PR DESCRIPTION
**Pull request by MCUdude**
Resolves #1472.

This PR allows the jtag2updi or any JTAG3 compatible programmer that speaks UPDI to read the chip silicon revision. pymcuprog already has this feature, and I thought it might be useful in case someone is chasing a silicon bug "ghost" and don't know the revision of their chip.

I've tested this PR with an AVR128DA48, AVR128DB48, ATtiny3217, and AVR64DD32 using the `pkobn_updi` programmer.

I've tested the AVR128DA32 and the ATmega4809 using the jtag2updi and the xplainedmini_updi programmer.

I still haven't been able to figure out how to add this feature to the serialUPDI programmer. I'm having a really hard time navigating the pymcuprog source code. If you have time @dbuchwald, could you please have a look at this?

<details>
<summary>pymcuprog output:</summary>

```
$ pymcuprog -d avr64dd32 ping -v info
Connecting to anything possible
Connected to nEDBG CMSIS-DAP from Microchip (serial number MC020019502HIP000497)
Debugger firmware version 1.23.91
Debugger hardware revision 0
Device mounted: 'avr64dd32'
pymcuprog.programmer - INFO - Setting up programming session for 'avr64dd32'
pymcuprog.deviceinfo.deviceinfo - INFO - Looking for device avr64dd32
pymcuprog.nvm - INFO - UPDI baud rate: 900000bps
pymcuprog.nvm - INFO - UPDI-specific initialiser
Pinging device...
pymcuprog.programmer - INFO - Reading device ID...
pymcuprog.serialupdi.application - INFO - SIB: 'AVR     P:2D:1-3M2 (A3.KV00K.0)'
pymcuprog.serialupdi.application - INFO - Device family ID: 'AVR'
pymcuprog.serialupdi.application - INFO - NVM interface: 'P:2'
pymcuprog.serialupdi.application - INFO - Debug interface: 'D:1'
pymcuprog.serialupdi.application - INFO - PDI oscillator: '3M2'
pymcuprog.serialupdi.application - INFO - Extra info: '(A3.KV00K.0)'
pymcuprog.nvm - INFO - PDI revision = 0x03
pymcuprog.nvm - INFO - Device ID: '1E961A'
pymcuprog.nvm - INFO - Device revision: '1.3'
Ping response: 1E961A
pymcupr
```

</details>

<details>
<summary>avrdude output:</summary>

```
$ ./avrdude -cpkobn_updi -pavr64dd32 -v

avrdude: Version 7.2-20230720
         Copyright the AVRDUDE authors;
         see https://github.com/avrdudes/avrdude/blob/main/AUTHORS

         System wide configuration file is /Users/hans/Downloads/avrdude/src/avrdude.conf
         User configuration file is /Users/hans/.avrduderc

         Using Port                    : usb
         Using Programmer              : pkobn_updi
avrdude: found CMSIS-DAP compliant device, using EDBG protocol
         AVR Part                      : AVR64DD32
         RESET disposition             : dedicated
         RETRY pulse                   : SCK
         Serial program mode           : yes
         Parallel program mode         : yes
         Memory Detail                 :

                                           Block Poll               Page                       Polled
           Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
           ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
           fuse0       wdtcfg      0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuse1       bodcfg      0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuse2       osccfg      0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuse5       syscfg0     0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuse6       syscfg1     0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuse7       codesize    0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuse8       bootsize    0     0     0    0 no          1    1      0     0     0 0x00 0x00
           fuses                   0     0     0    0 no          9   16      0     0     0 0x00 0x00
           lock                    0     0     0    0 no          4    1      0     0     0 0x00 0x00
           tempsense               0     0     0    0 no          2    1      0     0     0 0x00 0x00
           signature               0     0     0    0 no          3    1      0     0     0 0x00 0x00
           prodsig                 0     0     0    0 no        125  125      0     0     0 0x00 0x00
           sernum                  0     0     0    0 no         16    1      0     0     0 0x00 0x00
           userrow     usersig     0     0     0    0 no         32   32      0     0     0 0x00 0x00
           data                    0     0     0    0 no          0    1      0     0     0 0x00 0x00
           eeprom                  0     0     0    0 no        256    1      0     0     0 0x00 0x00
           flash                   0     0     0    0 no      65536  512      0     0     0 0x00 0x00

         Programmer Type : JTAGICE3_UPDI
         Description     : Curiosity nano (nEDBG) in UPDI mode
         ICE HW version  : 0
         ICE FW version  : 1.23 (rel. 91)
         Serial number   : MC020019502HIP000497
         Vtarget         : 5.01 V
         PDI/UPDI clk    : 100 kHz

avrdude: partial Family_ID returned: "AVR "
avrdude: silicon revision: 1.3
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1e961a (probably avr64dd32)

avrdude done.  Thank you.
```

</details>

### CODE REVIEW

**Comment by MCUdude** [comment]
BTW the `sernum` offset was incorrect for the megaAVR-0 and tinyAVR-0,1,2 so I fixed this as well.

**Comment by dbuchwald** [comment]
This is indeed interesting feature, @MCUdude, and I'm happy to look into it. Just give me couple of days to play with it and understand the code again :)

**Comment by MCUdude** [comment]
Excellent @dbuchwald!

**Comment by dbuchwald** [comment]
Hello, since this change in `serialupdi.c` requires your changes (definition of `syscfg_base`), I created PR against your repository here:

https://github.com/MCUdude/avrdude/pull/4/files

Have fun and let me know if there are any issues with this implementation.

**Comment by MCUdude** [comment]
Thank you for the PR @dbuchwald! I've tested it, merged it and it works flawlessly.

I think this PR is ready to be merged. Anyone else that wants to give this PR a try?

**Comment by mcuee** [comment]
Looks good for the AVR64EA48.

```
(py310x64venv) PS C:\work\avr\avrdude_test\avrdude_bin> pymcuprog -d avr64ea48 ping -v info
Connecting to anything possible
Connected to nEDBG CMSIS-DAP from Microchip (serial number MCHP3428031800001161)
Debugger firmware version 1.27.129
Debugger hardware revision 0
Device mounted: 'avr64ea48'
pymcuprog.programmer - INFO - Setting up programming session for 'avr64ea48'
pymcuprog.deviceinfo.deviceinfo - INFO - Looking for device avr64ea48
pymcuprog.nvm - INFO - UPDI baud rate: 900000bps
pymcuprog.nvm - INFO - UPDI-specific initialiser
Pinging device...
pymcuprog.programmer - INFO - Reading device ID...
pymcuprog.serialupdi.application - INFO - SIB: 'AVR     P:3D:1-3M2 (B1.59F02.0)'
pymcuprog.serialupdi.application - INFO - Device family ID: 'AVR'
pymcuprog.serialupdi.application - INFO - NVM interface: 'P:3'
pymcuprog.serialupdi.application - INFO - Debug interface: 'D:1'
pymcuprog.serialupdi.application - INFO - PDI oscillator: '3M2'
pymcuprog.serialupdi.application - INFO - Extra info: '(B1.59F02.0)'
pymcuprog.nvm - INFO - PDI revision = 0x03
pymcuprog.nvm - INFO - Device ID: '1E961E'
pymcuprog.nvm - INFO - Device revision: '2.1'
Ping response: 1E961E
pymcuprog.nvm - INFO - UPDI-specific de-initialiser
Done.
(py310x64venv) PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1474 -C .\avrdude_pr1474.conf -c pkobn_updi -p avr64ea48 -v

avrdude_pr1474: Version 7.2-20230725 (6c4414e6)
                Copyright the AVRDUDE authors;
                see https://github.com/avrdudes/avrdude/blob/main/AUTHORS

                System wide configuration file is C:\work\avr\avrdude_test\avrdude_bin\avrdude_pr1474.conf
                User configuration file is C:\work\avr\avrdude_test\avrdude_bin\avrdude.rc

                Using Port                    : usb
                Using Programmer              : pkobn_updi
avrdude_pr1474: found CMSIS-DAP compliant device, using EDBG protocol
                AVR Part                      : AVR64EA48
                RESET disposition             : dedicated
                RETRY pulse                   : SCK
                Serial program mode           : yes
                Parallel program mode         : yes
                Memory Detail                 :

                                                  Block Poll               Page                       Polled
                  Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
                  ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
                  fuse0       wdtcfg      0     0     0    0 no          1    1      0     0     0 0x00 0x00
                  fuse1       bodcfg      0     0     0    0 no          1    1      0     0     0 0x00 0x00
                  fuse2       osccfg      0     0     0    0 no          1    1      0     0     0 0x00 0x00
                  fuse5       syscfg0     0     0     0    0 no          1    1      0     0     0 0x00 0x00
                  fuse6       syscfg1     0     0     0    0 no          1    1      0     0     0 0x00 0x00
                  fuse7       codesize    0     0     0    0 no          1    1      0     0     0 0x00 0x00
                  fuse8       bootsize    0     0     0    0 no          1    1      0     0     0 0x00 0x00
                  fuses                   0     0     0    0 no          9   16      0     0     0 0x00 0x00
                  lock                    0     0     0    0 no          4    1      0     0     0 0x00 0x00
                  tempsense               0     0     0    0 no          2    1      0     0     0 0x00 0x00
                  signature               0     0     0    0 no          3    1      0     0     0 0x00 0x00
                  prodsig                 0     0     0    0 no        125  125      0     0     0 0x00 0x00
                  sernum                  0     0     0    0 no         16    1      0     0     0 0x00 0x00
                  userrow     usersig     0     0     0    0 no         64   64      0     0     0 0x00 0x00
                  data                    0     0     0    0 no          0    1      0     0     0 0x00 0x00
                  eeprom                  0     0     0    0 no        512    8      0     0     0 0x00 0x00
                  flash                   0     0     0    0 no      65536  128      0     0     0 0x00 0x00

                Programmer Type : JTAGICE3_UPDI
                Description     : Curiosity nano (nEDBG) in UPDI mode
                ICE HW version  : 0
                ICE FW version  : 1.27 (rel. 129)
                Serial number   : MCHP3428031800001161
                Vtarget         : 3.31 V
                PDI/UPDI clk    : 100 kHz

avrdude_pr1474: partial Family_ID returned: "AVR "
avrdude_pr1474: silicon revision: 2.1
avrdude_pr1474: AVR device initialized and ready to accept instructions
avrdude_pr1474: device signature = 0x1e961e (probably avr64ea48)

avrdude_pr1474 done.  Thank you.
```

**Comment by mcuee** [comment]
Good for the ATtiny817 as well.

```
(py310x64venv) PS C:\work\avr\avrdude_test\avrdude_bin> pymcuprog -d attiny817 ping -v info
Connecting to anything possible
Connected to EDBG CMSIS-DAP from ATMEL (serial number ATML2654061800002660)
Debugger firmware version 3.34.435
Debugger hardware revision 240
Device mounted: 'attiny817'
pymcuprog.programmer - INFO - Setting up programming session for 'attiny817'
pymcuprog.deviceinfo.deviceinfo - INFO - Looking for device attiny817
pymcuprog.nvm - INFO - UPDI baud rate: 900000bps
pymcuprog.nvm - INFO - UPDI-specific initialiser
Pinging device...
pymcuprog.programmer - INFO - Reading device ID...
pymcuprog.serialupdi.application - INFO - SIB: 'tinyAVR P:0D:0-3M2 (01.59B16.0)'
pymcuprog.serialupdi.application - INFO - Device family ID: 'tinyAVR'
pymcuprog.serialupdi.application - INFO - NVM interface: 'P:0'
pymcuprog.serialupdi.application - INFO - Debug interface: 'D:0'
pymcuprog.serialupdi.application - INFO - PDI oscillator: '3M2'
pymcuprog.serialupdi.application - INFO - Extra info: '(01.59B16.0)'
pymcuprog.nvm - INFO - PDI revision = 0x02
pymcuprog.nvm - INFO - Device ID: '1E9320'
pymcuprog.nvm - INFO - Device revision: '0.1'
Ping response: 1E9320
pymcuprog.nvm - INFO - UPDI-specific de-initialiser
Done.
(py310x64venv) PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1474 -C .\avrdude_pr1474.conf -c xplainedpro_updi -p t817 -v

avrdude_pr1474: Version 7.2-20230725 (6c4414e6)
                Copyright the AVRDUDE authors;
                see https://github.com/avrdudes/avrdude/blob/main/AUTHORS

                System wide configuration file is C:\work\avr\avrdude_test\avrdude_bin\avrdude_pr1474.conf
                User configuration file is C:\work\avr\avrdude_test\avrdude_bin\avrdude.rc

                Using Port                    : usb
                Using Programmer              : xplainedpro_updi
avrdude_pr1474: found CMSIS-DAP compliant device, using EDBG protocol
                AVR Part                      : ATtiny817
                RESET disposition             : dedicated
                RETRY pulse                   : SCK
                Serial program mode           : yes
                Parallel program mode         : yes
                Memory Detail                 :

                                                  Block Poll               Page                       Polled
                  Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
                  ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
                  fuse0       wdtcfg      0     0     0    0 no          1    1      0     0     0 0x00 0x00
                  fuse1       bodcfg      0     0     0    0 no          1    1      0     0     0 0x00 0x00
                  fuse2       osccfg      0     0     0    0 no          1    1      0     0     0 0x00 0x00
                  fuse5       syscfg0     0     0     0    0 no          1    1      0     0     0 0x00 0x00
                  fuse6       syscfg1     0     0     0    0 no          1    1      0     0     0 0x00 0x00
                  fuse7       append      0     0     0    0 no          1    1      0     0     0 0x00 0x00
                  fuse8       bootend     0     0     0    0 no          1    1      0     0     0 0x00 0x00
                  fuses                   0     0     0    0 no          9   10      0     0     0 0x00 0x00
                  lock                    0     0     0    0 no          1    1      0     0     0 0x00 0x00
                  tempsense               0     0     0    0 no          2    1      0     0     0 0x00 0x00
                  signature               0     0     0    0 no          3    1      0     0     0 0x00 0x00
                  prodsig                 0     0     0    0 no         61   61      0     0     0 0x00 0x00
                  sernum                  0     0     0    0 no         10    1      0     0     0 0x00 0x00
                  osccal16                0     0     0    0 no          2    1      0     0     0 0x00 0x00
                  osccal20                0     0     0    0 no          2    1      0     0     0 0x00 0x00
                  osc16err                0     0     0    0 no          2    1      0     0     0 0x00 0x00
                  osc20err                0     0     0    0 no          2    1      0     0     0 0x00 0x00
                  data                    0     0     0    0 no          0    1      0     0     0 0x00 0x00
                  userrow     usersig     0     0     0    0 no         32   32      0     0     0 0x00 0x00
                  eeprom                  0     0     0    0 no        128   32      0     0     0 0x00 0x00
                  flash                   0     0     0    0 no       8192   64      0     0     0 0x00 0x00
                  fuse4       tcd0cfg     0     0     0    0 no          1    1      0     0     0 0x00 0x00

                Programmer Type : JTAGICE3_UPDI
                Description     : Atmel AVR XplainedPro in UPDI mode
                ICE HW version  : 240
                ICE FW version  : 3.34 (rel. 435)
                Serial number   : ATML2654061800002660
                Vtarget         : 3.34 V
                PDI/UPDI clk    : 1000 kHz

avrdude_pr1474: partial Family_ID returned: "tiny"
avrdude_pr1474: silicon revision: 0.1
avrdude_pr1474: AVR device initialized and ready to accept instructions
avrdude_pr1474: device signature = 0x1e9320 (probably t817)

avrdude_pr1474 done.  Thank you.
```

**Comment by mcuee** [comment]
> I think this PR is ready to be merged. Anyone else that wants to give this PR a try?

@MCUdude 

This PR is good from my side. Thanks.

File: src/jtag3.c [hunk 1]
```diff
@@ -1421,6 +1421,11 @@ static int jtag3_initialize(const PROGRAMMER *pgm, const AVRPART *p) {
       /* Partial Family_ID has been returned */
       pmsg_notice("partial Family_ID returned: \"%c%c%c%c\"\n",
                   resp[3], resp[4], resp[5], resp[6]);
+
+      // Read chip silicon revision
+      char chip_rev[AVR_CHIP_REVLEN];
```
Comment (stefanrueger) [inline src/jtag3.c:1426]: Should this better be guarded like so
```
      if(pgm->read_chip_rev) {
        char chip_rev[AVR_CHIP_REVLEN];
        pgm->read_chip_rev(pgm, p, chip_rev);
        pmsg_notice("silicon revision: %x.%x\n", chip_rev[0] >> 4, chip_rev[0] & 0x0f);
      }
```

Comment (MCUdude) [reply src/jtag3.c:1426]: It is guarded by `if (p->prog_modes & PM_UPDI)`, but I can move the function call outside this and do it your way instead. It appears that Xmegas also have a revision number that can be read using a programmer. However, this is done a little differently, as the REVID byte is the next byte in memory after the signature. Perhaps we should add `revid` as a memory we can read from, and add it to the `read_chip_rev()` function?

From the Xmega A manual:

image

image

**Comment by MCUdude** [comment]
I managed to add the REVID memory to avrdude.conf, and be able to read it using a PDI or JTAG programmer using the EDBG protocol. I'll have to look into how I can accomplish the same using the jtagmkII protocol and the stk500v2 protocol.

```
./avrdude -cpowerdebugger -patxmega256a3bu -v

avrdude: Version 7.2-20230720
         Copyright the AVRDUDE authors;
         see https://github.com/avrdudes/avrdude/blob/main/AUTHORS

         System wide configuration file is /Users/hans/Downloads/avrdude/src/avrdude.conf
         User configuration file is /Users/hans/.avrduderc

         Using Port                    : usb
         Using Programmer              : powerdebugger
avrdude: found CMSIS-DAP compliant device, using EDBG protocol
         AVR Part                      : ATxmega256A3BU
         RESET disposition             : dedicated
         RETRY pulse                   : SCK
         Serial program mode           : yes
         Parallel program mode         : yes
         Memory Detail                 :

[...]

         Programmer Type : JTAGICE3
         Description     : Atmel PowerDebugger (ARM/AVR) in JTAG mode
         ICE HW version  : 1
         ICE FW version  : 1.61 (rel. 184)
         Serial number   :
         Vtarget         : 3.30 V
         JTAG clk Xmega  : 100 kHz
         Vout set        : 0.00 V
         Vout measured   : 1.47 V
         Ch A voltage    : 1.475 V
         Ch A current    : -1.059 mA
         Ch B voltage    : 1.525 V
         Ch B current    : 0.000 mA

avrdude: JTAG ID returned: 0x3f 0x30 0x84 0x69
avrdude: silicon revision: 0.6
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1e9843 (probably x256a3bu)

avrdude done.  Thank you.
```

```
./avrdude -cxplainedpro_pdi -patxmega128a1u -v

avrdude: Version 7.2-20230720
         Copyright the AVRDUDE authors;
         see https://github.com/avrdudes/avrdude/blob/main/AUTHORS

         System wide configuration file is /Users/hans/Downloads/avrdude/src/avrdude.conf
         User configuration file is /Users/hans/.avrduderc

         Using Port                    : usb
         Using Programmer              : xplainedpro_pdi
avrdude: found CMSIS-DAP compliant device, using EDBG protocol
         AVR Part                      : ATxmega128A1U
         RESET disposition             : dedicated
         RETRY pulse                   : SCK
         Serial program mode           : yes
         Parallel program mode         : yes
         Memory Detail                 :

         Programmer Type : JTAGICE3_PDI
         Description     : Atmel AVR XplainedPro in PDI mode
         ICE HW version  : 240
         ICE FW version  : 3.37 (rel. 438)
         Serial number   :
         Vtarget         : 3.29 V
         PDI/UPDI clk    : 1000 kHz

avrdude: silicon revision: 0.b
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1e974c (probably x128a1u)

avrdude done.  Thank you.
```

**Comment by MCUdude** [comment]
I've now updated the PR to support Xmegas as well. You can add `-v` to have Avrdude read and print the chip revision when avrdude is executed, or the `revid` memory can either be read in immediate mode or terminal mode.

Supported protocols are jtag3 (PDI and JTAG), stk500v2/xprog (PDI) and jtagmkii (PDI and JTAG).

Tested with a Power Debugger, AVRISPmkII, and an AVR dragon in PDI and JTAG mode.

Feel free to give it a try using your favorite Xmega-compatible programmer!

```
./avrdude -cdragon_jtag -patxmega256a3bu -v

avrdude: Version 7.2-20230720
         Copyright the AVRDUDE authors;
         see https://github.com/avrdudes/avrdude/blob/main/AUTHORS

         System wide configuration file is /Users/hans/Downloads/avrdude/src/avrdude.conf
         User configuration file is /Users/hans/.avrduderc

         Using Port                    : usb
         Using Programmer              : dragon_jtag
avrdude: usbdev_open(): found AVRDRAGON, serno:
JTAG ICE mkII sign-on message:
Communications protocol version: 1
M_MCU:
  boot-loader FW version:        255
  firmware version:              7.39
  hardware version:              1
S_MCU:
  boot-loader FW version:        255
  firmware version:              7.39
  hardware version:              2
Serial number:                   00:a2:00:00:0f:1a
Device ID:                       AVRDRAGON
         AVR Part                      : ATxmega256A3BU

[...] 

         Programmer Type : DRAGON_JTAG
         Description     : Atmel AVR Dragon in JTAG mode
         M_MCU HW version: 1
         M_MCU FW version: 7.39
         S_MCU HW version: 2
         S_MCU FW version: 7.39
         Serial number   : 
         Vtarget         : 3.3 V
         JTAG clock      : 891.7 kHz (1.1 us)
JTAG ICE mkII sign-on message:
Communications protocol version: 1
M_MCU:
  boot-loader FW version:        255
  firmware version:              7.39
  hardware version:              1
S_MCU:
  boot-loader FW version:        255
  firmware version:              7.39
  hardware version:              2
Serial number:                   00:a2:00:00:0f:1a
Device ID:                       AVRDRAGON
avrdude: silicon revision: 0.6
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1e9843 (probably x256a3bu)

avrdude done.  Thank you.
```

**Comment by MCUdude** [comment]
One thing I just realized I haven't made sure that Avrdude won't attempt to read the chip revision(`revid`) when using JTAG and connected to a classic part. Will look at this tomorrow.

**Comment by mcuee** [comment]
@MCUdude 

Yes this PR is good for xmega.
```
PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1474v1 -C .\avrdude_pr1474v1.conf -c avrispmkii -p x32a4 -v

avrdude_pr1474v1: Version 7.2-20230729 (86a1aa1b)
                  Copyright the AVRDUDE authors;
                  see https://github.com/avrdudes/avrdude/blob/main/AUTHORS

                  System wide configuration file is C:\work\avr\avrdude_test\avrdude_bin\avrdude_pr1474v1.conf
                  User configuration file is C:\work\avr\avrdude_test\avrdude_bin\avrdude.rc

                  Using Port                    : usb
                  Using Programmer              : avrispmkII
avrdude_pr1474v1: usbdev_open(): found AVRISP mkII, serno: 00000000193B
                  AVR Part                      : ATxmega32A4
                  RESET disposition             : dedicated
                  RETRY pulse                   : SCK
                  Serial program mode           : yes
                  Parallel program mode         : yes
                  Memory Detail                 :

                                                    Block Poll               Page                       Polled
                    Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
                    ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
                    fuse1                   0     0     0    0 no          1    1      0     0     0 0x00 0x00
                    fuse2                   0     0     0    0 no          1    1      0     0     0 0x00 0x00
                    fuse4                   0     0     0    0 no          1    1      0     0     0 0x00 0x00
                    fuse5                   0     0     0    0 no          1    1      0     0     0 0x00 0x00
                    lock                    0     0     0    0 no          1    1      0     0     0 0x00 0x00
                    signature               0     0     0    0 no          3    1      0     0     0 0x00 0x00
                    revid                   0     0     0    0 no          1    1      0     0     0 0x00 0x00
                    prodsig                 0     0     0    0 no         50   50      0     0     0 0x00 0x00
                    data                    0     0     0    0 no          0    1      0     0     0 0x00 0x00
                    fuse0                   0     0     0    0 no          1    1      0     0     0 0x00 0x00
                    eeprom                  0     0     0    0 no       1024   32      0     0     0 0x00 0x00
                    flash                   0     0     0    0 no      36864  256      0     0     0 0x00 0x00
                    application             0     0     0    0 no      32768  256      0     0     0 0x00 0x00
                    apptable                0     0     0    0 no       4096  256      0     0     0 0x00 0x00
                    boot                    0     0     0    0 no       4096  256      0     0     0 0x00 0x00
                    usersig                 0     0     0    0 no        256  256      0     0     0 0x00 0x00

                  Programmer Type : STK500V2
                  Description     : Atmel AVR ISP mkII
                  Programmer Model: AVRISP mkII
                  Hardware Version: 1
                  Serial number   : 00000000193B
                  Firmware Version Controller : 1.24
                  Vtarget         : 3.3 V
                  SCK period      : 8.00 us
avrdude_pr1474v1: silicon revision: 0.4
avrdude_pr1474v1: AVR device initialized and ready to accept instructions
avrdude_pr1474v1: device signature = 0x1e9541 (probably x32a4)

avrdude_pr1474v1 done.  Thank you.
```

**Comment by mcuee** [comment]
@stefanrueger 

This PR is good to go from my side.

File: src/avr.c [hunk 2]
```diff
@@ -1405,6 +1405,7 @@ const char *avr_mem_order[100] = {
   "tempsense",    "signature",    "prodsig",      "sernum",
   "calibration",  "osccal16",     "osccal20",     "osc16err",
   "osc20err",     "usersig",      "userrow",      "data",
+  "revid",
```
Comment (stefanrueger) [inline src/avr.c:1408]: I don't think this is right - see longer comment below

**Comment by stefanrueger** [comment]
TLDR; How about introducing a new memory `io` that caters for all I/O memory including MCU registers, so one can execute `-U io:r:-:h` or terminal `save io <add> <len> -:h` to show a particular io region. The next step would be using the .ATDF files to map the location of a particular register within `io`, so that, eg, the revision ID can be accessed in the terminal as `register syscfg.revid` (modern AVRs) or `register mcu.revid` (XMEGAs).

The long of it: Is `revid` really a memory in the sense of the data sheets? They seem to disagree:

For the modern AVRs, the data sheets list `REVID` as part of *system configuration registers* collectively called `SYSCFG` (not to be confused with the `SYSCFG0` and `SYSCFG1` fuses). Interestingly, the data sheet for the ATmega4808 has `REVID` as the only register in that block. The corresponding .ATDF file reports sibling registers External Break register `EXTBRK`, OCD Message Register `OCDM` and OCD Message Status `OCDMS`.

The ATxmega A...E series each has `REVID` as forth byte in the MCU Control register block tight behind `DEVID0`, `DEVID1` and `DEVID2` (the signature!). Depending on the series, A-E, there are other illustrious siblings of `REVID`:  `ANAINIT`, `AWEXLOCK`, `EVSYSLOCK`, `FAULTLOCK`, `JTAGUID`, `MCUCR`, `WEXLOCK`.

The C headers for the XMEGAs and modern AVRs model register groups as structures, so that for an ATmega4808 one would reference the Revision ID byte as `SYSCFG.REVID` whilst for an ATxmega128A1U this would be `MCU.REVID`.

It looks like external programmers can read registers of the MCU for XMEGAs and modern AVR, and this is what this PR does. It is a singular solution to a singular problem (what's the Revision ID?).  Introducing a new memory each time someone needs a register, say `jtaguid` for `MCU.JTAGUID` looks like the wrong approach to me. This clutters both the code base and avrdude.conf neither is it scalable: there are tons of register *groups*, for example, the
 - XMEGA A series has `GPIO`, `OCD`, `CPU`, `CLK`, `PR`, `SLEEP`, `OSC`, `DFLLRC32M`, `DFLLRC2M`, `RST`, `WDT`, `MCU`, `PMIC`, `DMA`, `EVSYS`, `NVM`, `FUSE`, `LOCKBIT`, `PROD_SIGNATURES`, `ACA`, `ACB`, `ADCA`, `ADCB`, `DACA`, `DACB`, `RTC`, `EBI`, `TWIC`, `TWID`, `TWIE`, `TWIF`, `PORTCFG`, `VPORT0`, `VPORT1`, `VPORT2`, `VPORT3`, `PORTA`, `PORTB`, `PORTC`, `PORTD`, `PORTE`, `PORTF`, `PORTH`, `PORTJ`, `PORTK`, `PORTQ`, `PORTR`, `TCC0`, `TCC1`, `AWEXC`, `HIRESC`, `TCD0`, `TCD1`, `HIRESD`, `TCE0`, `TCE1`, `AWEXE`, `HIRESE`, `TCF0`, `TCF1`, `HIRESF`, `USARTC0`, `USARTC1`, `USARTD0`, `USARTD1`, `USARTE0`, `USARTE1`, `USARTF0`, `USARTF1`, `SPIC`, `SPID`, `SPIE`, `SPIF`, `IRCOM`, `AES`
 - The ATmega48 has `AC0`, `ADC0`, `BOD`, `CCL`, `CLKCTRL`, `CPU`, `CPUINT`, `CRCSCAN`, `EVSYS`, `FUSE`, `GPIO`, `LOCKBIT`, `NVMCTRL`, `PORTA`, `PORTB`, `PORTC`, `PORTD`, `PORTE`, `PORTF`, `PORTMUX`, `RSTCTRL`, `RTC`, `SIGROW`, `SLPCTRL`, `SPI0`, `SYSCFG`, `TCA0`, `TCB0`, `TCB1`, `TCB2`, `TWI0`, `USART0`, `USART1`, `USART2`, `USERROW`, `VPORTA`, `VPORTB`, `VPORTC`, `VPORTD`, `VPORTE`, `VPORTF`, `VREF`, `WDT`

Turns out some of the registers in these groups are initialised at reset with the contents of corresponding fuses.

Where am I getting at?

I propose to afford AVRDUDE with the notion of a new `io` memory that jtag, pdi and updi programmers access, ie, their bytewise read and write functions need extending. This way users can access this memory in full using `-U` or at a byte granularity using, eg, terminal `write io <addr> <data>` and `save io <addr> <len> -:h`.

Then, it would also be possible to create a mapping within AVRDUDE (a la avrintel.c) that maps the terminal command `register mcu.revid` to accessing the right offset in the `io` memory.

This would be generic, yet part-specific and driven by .ATDF files. It might allow the user to do all sorts of things, eg, poke around the PORTx register groups of a board in situ to open the gate for the crocodile enclosure right from the comfort of the AVRDUDE terminal.

So, how would we do this if we want to go along this road? I reckon this would be three parts in at least three separate PRs
 - Introduce `io` memory and provide code to access it in jtag, pdi and updi programmers (this PR has all the right ingredients for this)
 - Map symbolic register names to io memory offsets and provide a `register` command in the terminal (I can do this)
 - Map bitfield names of each register (if any) and access the bitfields similar to the terminal `config` command (let's see)

Below relevant images from data sheets for the layout of the I/O memory `io`.

**Comment by MCUdude** [comment]
To be honest, I haven't been completely satisfied with this PR, because it's only possible to get the silicon revision by reading the output when using -v. Being able to read it as a memory, or part of a memory block would be much, much better.

> TLDR; How about introducing a new memory io that caters for all I/O memory including MCU registers, so one can execute -U io:r:-:h or terminal save io <add> <len> -:h to show a particular io region. The next step would be using the .ATDF files to map the location of a particular register within io, so that, eg, the revision ID can be accessed in the terminal as register syscfg.revid (modern AVRs) or register mcu.revid (XMEGAs).

This would be really, really cool! I'd love to close this PR in favor of something like this! So this would mean that one could write to, let's say, the PORTn.OUT register, which results in physical pin changes in real-time?

**Comment by stefanrueger** [comment]
> in favor of something like this

Cool. *But note* I cannot write the code for r/w of the io memory. The pgm->read_byte(0 and pgm->write_byte() functions need extending by someone with parts, data sheets, jtag/pdi/updi programmers and C skills. I can do the rest from the .atdf files.

**Comment by MCUdude** [comment]
> But note I cannot write the code for r/w of the io memory. The pgm->read_byte() and pgm->write_byte() functions need extending by someone with parts, data sheets, jtag/pdi/updi programmers and C skills.

I can deal with the low-level functions of the various protocols (edbg, jtag2, sk500v2 and serialupdi)! I'm already able to read and write to the entire IOREG section (0 - 0x1000) on an ATmega4808 using a Power Debugger.

**Comment by MCUdude** [comment]
| IOREG   | MegaAVR-0 | TinyAVR-0 | TinyAVR-1 | TinyAVR-2 | AVR-DA | AVR-DB | AVR-DD | AVR-EA |
|--|------------------|-|-|-|-|-|-|-|
| **Start address** | 0x0000 | 0x0000 | 0x0000 | 0x0000 | 0x0000 | 0x0000 | 0x0000 | 0x0000 |
| **End address** | 0x0FFF |0x0FFF |0x0FFF |0x107F | 0x103F | 0x103F | 0x103F | 0x103F |

So would this be enough (where `size` is changed depending on chip family)?

```
    memory "io"
        size               = 0x1000;
        offset             = 0x0000;
        readsize           = 1;
    ;
```

**Comment by MCUdude** [comment]
> BTW, I don't think this PR should be closed. I'd just say we should not invent a revid memory for the XMEGAs. if the programmer function gets at the relevant byte otherwise, it is still fine to have this PR.

Sure! So instead of reading revid like this (pgm->read_chip_rev):
```c
  // XMEGA using JTAG or PDI
  else if (p->prog_modes & PM_PDI) {
    AVRMEM *m = avr_locate_mem(p, "revid");
    if ((status = pgm->read_byte(pgm, p, m, 0, (unsigned char *)chip_rev)) < 0) {
      return status;
    }
  }
```

You'd want this instead, given that I add `io` as a memory that can be read/written?

```c
  // XMEGA using JTAG or PDI
  else if (p->prog_modes & PM_PDI) {
    AVRMEM *m = avr_locate_mem(p, "io");
    if ((status = pgm->read_byte(pgm, p, m+p->syscfg_base+1, 0, (unsigned char *)chip_rev)) < 0) {
      return status;
    }
  }
```

or without `p->syscfg_base`:

```c
  // XMEGA using JTAG or PDI
  else if (p->prog_modes & PM_PDI) {
    AVRMEM *m = avr_locate_mem(p, "io");
    if ((status = pgm->read_byte(pgm, p, m+0x0f01, 0, (unsigned char *)chip_rev)) < 0) {
      return status;
    }
  }
```

So do you want me to add `io` to all PDI and UPDI parts according to the table I posted previously? And do you want me to remove `syscfg_base` and instead use `0x0f00+1` or `0x0f01`?

**Comment by stefanrueger** [comment]
I think it would be cool to have `io` as a memory instead of `revid` where possible, so yes, definitely for XMEGAs and AVR8X parts. Would be fab if all jtag, pdi and updi programmers were able to access `io`. The volatile memory `io` could in theory also be useful for classic parts but, alas, there are (to the best of my knowledge) no external programmer interfaces that allow access to the data address space of classic parts *except* for bootloaders, which could in theory provide access but afaik in practice don't. 

As to `syscfg_base` there is precedence for that kind of information to make it into `avrdude.conf` though that does not appear to vary with the part, so could well be a `#define` constant. 

Above code should probably be
```
if ((status = pgm->read_byte(pgm, p, m, p->mcu_base+3, (unsigned char *)chip_rev)) < 0)
      return status;
```
for XMEGAs and
```
if ((status = pgm->read_byte(pgm, p, m, p->syscfg_base+1, (unsigned char *)chip_rev)) < 0)
      return status;
```
for AVR8X.

**Comment by MCUdude** [comment]
Sure, I'll update this PR tonight

**Comment by MCUdude** [comment]
@stefanrueger I've now done major changes to this PR. `io` is now added, and `revid` is removed.

I have no issues issues with the UPDI programmers, and I can read and write to the `io` memory. However, when connected to an Xmega, I can only read the IO memory and not write to it. This is true for all three protocols, `jtag3`, `jtagmkii` and `stk500v2`. I've tried to look into the documentation, but I've not been able to figure it out. (I've tried a bunch if different memory types and offsets, but nothing helps).

I've tested using the following programmers against the ATxmega128A3U:
* `powerdebugger_pdi`
* `dragon_pdi`
* `avrispmkii`

I've tested the following programmers against the ATmega4808:
* `powerdebugger_updi`
* `jtag2updi`

**Comment by stefanrueger** [comment]
Very good. We also should document the new `io` memory in avrdude.1 and avrdude.texi

> Xmega, I can only read the IO memory and not write to it

We can document that AVRDUDE is unable to write to XMEGA `io`. Are other programmers able to? That is, is it a matter of the XMEGA parts or a matter of the programmer? What do the general data sheets for the XMEGA series A...E say?

**Comment by stefanrueger** [comment]
> write to, let's say, the PORTn.OUT register

And, ... have you been able to open the gate of the crocodile enclosure using the `io` memory?

**Comment by stefanrueger** [comment]
BTW, the avrdude.conf file is no longer in canonical form after this PR. The order in which memories are listed by `-p*/s` is given by the order in this list

https://github.com/avrdudes/avrdude/blob/330030ed234bb2318fcc0e7d3f1805d1ab89345e/src/avr.c#L1396-L1408

Putting "io" after "data" is fitting b/c both are volatile memories. Hence, I'd suggest to put the "io" memory last in the part definitions. Pro tip: type `avrdude -p*/s >/tmp/parts` and replace the second part of avrdude.conf.in with the contents of the file `/tmp/parts`. That's what I do to ensure `avrdude.conf` stays in canonical form

**Comment by MCUdude** [comment]
> We can document that AVRDUDE is unable to write to XMEGA io. Are other programmers able to? That is, is it a matter of the XMEGA parts or a matter of the programmer? What do the general data sheets for the XMEGA series A...E say?

@xedbg do you know if it is even possible to write to the XMEGA IO registers (PORTD.DIR, PORTD.SET etc.) using the jtag3, stk500v2, or the jtagmkII protocol? The protocol documentation for any of these isn't very clear regarding this.|

> And, ... have you been able to open the gate of the crocodile enclosure using the io memory?

Yes, I have. but only on AVRs that have UPDI. However, I think there are bit masks that I have to deal with because you can't write _any_ value to _any_ memory location.

**Comment by xedbg** [comment]
@MCUdude interesting question.  Its been a while, so I can't be sure; but XMEGA devices are quite similar to UPDI devices in many ways, so I would expect that its possible.  What is possible and what is useful has to be taken in the context of the Microchip IDE, so writing IO while not in debug mode makes no sense to Studio or MPLAB (but of course may for avrdude).
However, the debugger will block writing memory all memories while the core is running with xmega parts (unnecessary, but how it is), but programming mode is NOT running... so this should work... unless its the device itself that refuses it.  Does it fail silently, or with an error code?

**Comment by MCUdude** [comment]
@xedbg It tries to write the value but it gets a mismatch error. Not much I can work on. I've tried with and without the "SRAM" offset (0x1000000), with no luck. And I don't need the SRAM offset when writing to the AVR8X IO registers.
So it's clear that either the XMEGAs need a different write procedure (different write MTYPE, or a different offset?), or it doesn't work at all.

```
avrdude> write io 0x641 0xff # Set PORTD_DIRSET to 0xff
avrdude: (write) writing 1 byte starting from address 0x641
avrdude: jtag3_write_byte(.., io, 0x641, ...)
avrdude: sending write memory command: 0x80 (3 bytes msg)
avrdude: jtag3_read_byte(.., io, 0x641, ...)
avrdude: sending read memory command: 0x84 (5 bytes msg)
avrdude cmd_write() error: (write) verification error writing 0xff at 0x00641 cell=0x00
```

```c
// From jtag3_write_byte()
else if (strcmp(mem->desc, "io") == 0) {
    cmd[3] = MTYPE_SRAM;
    //AVRMEM *data = avr_locate_mem(p, "data");
    //addr += data->offset;
  }
```

**Comment by xedbg** [comment]
Hmmm.  I suspect there is a gating in silicon in that case, but can't confirm without asking an expert...
(SRAM memtype is the right one - there is an undocumented variant (0xB7) which is the same but without that offset, which is worth a try, but a long shot)

**Comment by stefanrueger** [comment]
Sanity check: The following table shows the parts by their `io` size; is that the same as [above](https://github.com/avrdudes/avrdude/pull/1474#issuecomment-1660931360)?
| `io` size | Parts |
| --: | :-- |
| 4096 | ATxmega16A4U ATxmega16C4 ATxmega16D4 ATxmega16A4 ATxmega32A4U ATxmega32C4 ATxmega32D4 ATxmega32A4 ATxmega64A4U ATxmega32C3 ATxmega32D3 ATxmega64C3 ATxmega64D3 ATxmega64D4 ATxmega64A1 ATxmega64A1U ATxmega64A3 ATxmega64A3U ATxmega64A4 ATxmega64B1 ATxmega64B3 ATxmega128C3 ATxmega128D3 ATxmega128D4 ATxmega128A1 ATxmega128A1revD ATxmega128A1U ATxmega128A3 ATxmega128A3U ATxmega128A4 ATxmega128A4U ATxmega128B1 ATxmega128B3 ATxmega192C3 ATxmega192D3 ATxmega192A1 ATxmega192A3 ATxmega192A3U ATxmega256C3 ATxmega256D3 ATxmega256A1 ATxmega256A3 ATxmega256A3U ATxmega256A3B ATxmega256A3BU ATxmega384C3 ATxmega384D3 ATxmega8E5 ATxmega16E5 ATxmega32E5 ATtiny202 ATtiny204 ATtiny402 ATtiny404 ATtiny406 ATtiny804 ATtiny806 ATtiny807 ATtiny1604 ATtiny1606 ATtiny1607 ATtiny212 ATtiny214 ATtiny412 ATtiny414 ATtiny416 ATtiny416auto ATtiny417 ATtiny814 ATtiny816 ATtiny817 ATtiny1614 ATtiny1616 ATtiny1617 ATtiny3216 ATtiny3217 ATmega808 ATmega809 ATmega1608 ATmega1609 ATmega3208 ATmega3209 ATmega4808 ATmega4809|
| 4160 | AVR32DA28 AVR32DA32 AVR32DA48 AVR64DA28 AVR64DA32 AVR64DA48 AVR64DA64 AVR128DA28 AVR128DA32 AVR128DA48 AVR128DA64 AVR32DB28 AVR32DB32 AVR32DB48 AVR64DB28 AVR64DB32 AVR64DB48 AVR64DB64 AVR128DB28 AVR128DB32 AVR128DB48 AVR128DB64 AVR16DD14 AVR16DD20 AVR16DD28 AVR16DD32 AVR32DD14 AVR32DD20 AVR32DD28 AVR32DD32 AVR64DD14 AVR64DD20 AVR64DD28 AVR64DD32 AVR8EA28 AVR8EA32 AVR16EA28 AVR16EA32 AVR16EA48 AVR32EA28 AVR32EA32 AVR32EA48 AVR64EA28 AVR64EA32 AVR64EA48|
| 4224 | ATtiny424 ATtiny426 ATtiny427 ATtiny824 ATtiny826 ATtiny827 ATtiny1624 ATtiny1626 ATtiny1627 ATtiny3224 ATtiny3226 ATtiny3227|

**Comment by MCUdude** [comment]
> Hmmm. I suspect there is a gating in silicon in that case, but can't confirm without asking an expert...
(SRAM memtype is the right one - there is an undocumented variant (0xB7) which is the same but without that offset, which is worth a try, but a long shot)

@xedbg I tried 0xB7 as well (`AVR8_MEMTYPE_TBUS` according to pyedbglib), with and without the 0x1000000 offset, and it didn't work either.

> Sanity check: The following table shows the parts by their io size; is that the same as https://github.com/avrdudes/avrdude/pull/1474#issuecomment-1660931360?

I had a look at the family datasheets, and I'm pretty sure I've gotten the sizes right. Feel free to double check!

**Comment by stefanrueger** [comment]
> gotten the sizes right

Good, I put the table there to ward off inheritance errors.

**Comment by stefanrueger** [comment]
@MCUdude You were right about the merge conflicts. Thanks for dealing with them.

I did another sanity cross check of the `io` sizes against the .atdf files:

| `io` start | `io` size | No of parts | Parts |
| --: | :-- | --: | :-- |
| 0x00 | 0x1000 | 45 | ATxmega128A1 ATxmega128A1U ATxmega128A3 ATxmega128A3U ATxmega128A4U ATxmega128B1 ATxmega128B3 ATxmega128C3 ATxmega128D3 ATxmega128D4 ATxmega16A4 ATxmega16A4U ATxmega16C4 ATxmega16D4 ATxmega16E5 ATxmega192A3 ATxmega192A3U ATxmega192C3 ATxmega192D3 ATxmega256A3 ATxmega256A3B ATxmega256A3BU ATxmega256A3U ATxmega256C3 ATxmega256D3 ATxmega32A4 ATxmega32A4U ATxmega32C3 ATxmega32C4 ATxmega32D3 ATxmega32D4 ATxmega32E5 ATxmega384C3 ATxmega384D3 ATxmega64A1 ATxmega64A1U ATxmega64A3 ATxmega64A3U ATxmega64A4U ATxmega64B1 ATxmega64B3 ATxmega64C3 ATxmega64D3 ATxmega64D4 ATxmega8E5 |
| 0x00 | 0x103f(!) | 43 | AVR128DA28 AVR128DA32 AVR128DA48 AVR128DA64 AVR128DB28 AVR128DB32 AVR128DB48 AVR128DB64 AVR16DD14 AVR16DD20 AVR16DD28 AVR16DD32 AVR16EA28 AVR16EA32 AVR16EA48 AVR32DA28 AVR32DA32 AVR32DA48 AVR32DB28 AVR32DB32 AVR32DB48 AVR32DD14 AVR32DD20 AVR32DD28 AVR32DD32 AVR32EA28 AVR32EA32 AVR32EA48 AVR64DA28 AVR64DA32 AVR64DA48 AVR64DA64 AVR64DB28 AVR64DB32 AVR64DB48 AVR64DB64 AVR64DD14 AVR64DD20 AVR64DD28 AVR64DD32 AVR64EA28 AVR64EA32 AVR64EA48 |
| 0x00 | 0x1100 | 46 | ATmega1608 ATmega1609 ATmega3208 ATmega3209 ATmega4808 ATmega4809 ATmega808 ATmega809 ATtiny1604 ATtiny1606 ATtiny1607 ATtiny1614 ATtiny1616 ATtiny1617 ATtiny1624 ATtiny1626 ATtiny1627 ATtiny202 ATtiny204 ATtiny212 ATtiny214 ATtiny3216 ATtiny3217 ATtiny3224 ATtiny3226 ATtiny3227 ATtiny402 ATtiny404 ATtiny406 ATtiny412 ATtiny414 ATtiny416 ATtiny416auto ATtiny417 ATtiny424 ATtiny426 ATtiny427 ATtiny804 ATtiny806 ATtiny807 ATtiny814 ATtiny816 ATtiny817 ATtiny824 ATtiny826 ATtiny827 |
| 0x00 | 0x0040 | 11 | ATtiny10 ATtiny102 ATtiny104 ATtiny11 ATtiny12 ATtiny15 ATtiny20 ATtiny4 ATtiny40 ATtiny5 ATtiny9 |
| 0x20 | 0x0040 | 31 | ATmega16 ATmega16A ATmega32 ATmega32A ATmega8 ATmega8515 ATmega8535 ATmega8A ATtiny13 ATtiny13A ATtiny2313 ATtiny2313A ATtiny24 ATtiny24A ATtiny25 ATtiny26 ATtiny261 ATtiny261A ATtiny28 ATtiny4313 ATtiny43U ATtiny44 ATtiny44A ATtiny45 ATtiny461 ATtiny461A ATtiny84 ATtiny84A ATtiny85 ATtiny861 ATtiny861A |
| 0x20 | 0x00e0 | 127 | AT90CAN128 AT90CAN32 AT90CAN64 AT90PWM1 AT90PWM161 AT90PWM216 AT90PWM2B AT90PWM3 AT90PWM316 AT90PWM3B AT90PWM81 AT90USB1286 AT90USB1287 AT90USB162 AT90USB646 AT90USB647 AT90USB82 ATA5272 ATA5505 ATA5790 ATA5790N ATA5791 ATA5795 ATA6285 ATA6286 ATA6612C ATA6613C ATA6614Q ATA6616C ATA6617C ATA664251 ATmega128 ATmega1284 ATmega1284P ATmega128A ATmega162 ATmega164A ATmega164P ATmega164PA ATmega165A ATmega165P ATmega165PA ATmega168 ATmega168A ATmega168P ATmega168PA ATmega168PB ATmega169A ATmega169P ATmega169PA ATmega16HVA ATmega16HVB ATmega16HVBrevB ATmega16M1 ATmega16U2 ATmega16U4 ATmega324A ATmega324P ATmega324PA ATmega324PB ATmega325 ATmega3250 ATmega3250A ATmega3250P ATmega3250PA ATmega325A ATmega325P ATmega325PA ATmega328 ATmega328P ATmega328PB ATmega329 ATmega3290 ATmega3290A ATmega3290P ATmega3290PA ATmega329A ATmega329P ATmega329PA ATmega32C1 ATmega32HVB ATmega32HVBrevB ATmega32M1 ATmega32U2 ATmega32U4 ATmega406 ATmega48 ATmega48A ATmega48P ATmega48PA ATmega48PB ATmega64 ATmega644 ATmega644A ATmega644P ATmega644PA ATmega645 ATmega6450 ATmega6450A ATmega6450P ATmega645A ATmega645P ATmega649 ATmega6490 ATmega6490A ATmega6490P ATmega649A ATmega649P ATmega64A ATmega64C1 ATmega64HVE2 ATmega64M1 ATmega88 ATmega88A ATmega88P ATmega88PA ATmega88PB ATmega8HVA ATmega8U2 ATtiny1634 ATtiny167 ATtiny441 ATtiny48 ATtiny828 ATtiny841 ATtiny87 ATtiny88 |
| 0x20 | 0x01e0 | 26 | ATA5700M322 ATA5702M322 ATA5781 ATA5782 ATA5783 ATA5787 ATA5831 ATA5832 ATA5833 ATA5835 ATA8210 ATA8215 ATA8510 ATA8515 ATmega1280 ATmega1281 ATmega1284RFR2 ATmega128RFA1 ATmega128RFR2 ATmega2560 ATmega2561 ATmega2564RFR2 ATmega256RFR2 ATmega640 ATmega644RFR2 ATmega64RFR2 |

Ignoring the classic parts for now (I will deal with them in an automated way for completeness later) there are still differences between the .atdf files and this PR *but* I think this PR is right. The 0x103f size looks wrong (probably caused by mistaking the last address for the size of a memory).

**Comment by MCUdude** [comment]
@stefanrueger I've now resolved the merge conflict, so the PR is now ready.

**Comment by MCUdude** [comment]
Wait, why is the size of IO 0x1100 for megaAVR0 and tinyAVR0/1/2? This doesn't comply with the information provided in the datasheet! What's correct, and what isn't?

From ioavr128da48.h:

```c
/* NVMCTRL - Non-volatile Memory Controller */
#define NVMCTRL_CTRLA  _SFR_MEM8(0x1000)
#define NVMCTRL_CTRLB  _SFR_MEM8(0x1001)
#define NVMCTRL_STATUS  _SFR_MEM8(0x1002)
#define NVMCTRL_INTCTRL  _SFR_MEM8(0x1003)
#define NVMCTRL_INTFLAGS  _SFR_MEM8(0x1004)
#define NVMCTRL_DATA  _SFR_MEM16(0x1006)
#define NVMCTRL_DATAL  _SFR_MEM8(0x1006)
#define NVMCTRL_DATAH  _SFR_MEM8(0x1007)
#define NVMCTRL_ADDR  _SFR_MEM32(0x1008)
#define NVMCTRL_ADDR0  _SFR_MEM8(0x1008)
#define NVMCTRL_ADDR1  _SFR_MEM8(0x1009)
#define NVMCTRL_ADDR2  _SFR_MEM8(0x100A)
#define NVMCTRL_ADDR3  _SFR_MEM8(0x100B)


/* LOCK - Lockbits */
#define LOCK_KEY  _SFR_MEM32(0x1040)
#define LOCK_KEY0  _SFR_MEM8(0x1040)
#define LOCK_KEY1  _SFR_MEM8(0x1041)
#define LOCK_KEY2  _SFR_MEM8(0x1042)
#define LOCK_KEY3  _SFR_MEM8(0x1043)
```

From iom4809.h:

```c
/* SYSCFG - System Configuration Registers */
#define SYSCFG_REVID  _SFR_MEM8(0x0F01)
#define SYSCFG_EXTBRK  _SFR_MEM8(0x0F02)
#define SYSCFG_OCDM  _SFR_MEM8(0x0F18)
#define SYSCFG_OCDMS  _SFR_MEM8(0x0F19)


/* NVMCTRL - Non-volatile Memory Controller */
#define NVMCTRL_CTRLA  _SFR_MEM8(0x1000)
#define NVMCTRL_CTRLB  _SFR_MEM8(0x1001)
#define NVMCTRL_STATUS  _SFR_MEM8(0x1002)
#define NVMCTRL_INTCTRL  _SFR_MEM8(0x1003)
#define NVMCTRL_INTFLAGS  _SFR_MEM8(0x1004)
#define NVMCTRL_DATA  _SFR_MEM16(0x1006)
#define NVMCTRL_DATAL  _SFR_MEM8(0x1006)
#define NVMCTRL_DATAH  _SFR_MEM8(0x1007)
#define NVMCTRL_ADDR  _SFR_MEM16(0x1008)
#define NVMCTRL_ADDRL  _SFR_MEM8(0x1008)
#define NVMCTRL_ADDRH  _SFR_MEM8(0x1009)


/* SIGROW - Signature row */
#define SIGROW_DEVICEID0  _SFR_MEM8(0x1100)
#define SIGROW_DEVICEID1  _SFR_MEM8(0x1101)
#define SIGROW_DEVICEID2  _SFR_MEM8(0x1102)
#define SIGROW_SERNUM0  _SFR_MEM8(0x1103)
#define SIGROW_SERNUM1  _SFR_MEM8(0x1104)
#define SIGROW_SERNUM2  _SFR_MEM8(0x1105)
#define SIGROW_SERNUM3  _SFR_MEM8(0x1106)
#define SIGROW_SERNUM4  _SFR_MEM8(0x1107)
#define SIGROW_SERNUM5  _SFR_MEM8(0x1108)
#define SIGROW_SERNUM6  _SFR_MEM8(0x1109)
#define SIGROW_SERNUM7  _SFR_MEM8(0x110A)
#define SIGROW_SERNUM8  _SFR_MEM8(0x110B)
#define SIGROW_SERNUM9  _SFR_MEM8(0x110C)
#define SIGROW_OSCCAL32K  _SFR_MEM8(0x1114)
#define SIGROW_OSCCAL16M0  _SFR_MEM8(0x1118)
#define SIGROW_OSCCAL16M1  _SFR_MEM8(0x1119)
#define SIGROW_OSCCAL20M0  _SFR_MEM8(0x111A)
#define SIGROW_OSCCAL20M1  _SFR_MEM8(0x111B)
#define SIGROW_TEMPSENSE0  _SFR_MEM8(0x1120)
#define SIGROW_TEMPSENSE1  _SFR_MEM8(0x1121)
#define SIGROW_OSC16ERR3V  _SFR_MEM8(0x1122)
#define SIGROW_OSC16ERR5V  _SFR_MEM8(0x1123)
#define SIGROW_OSC20ERR3V  _SFR_MEM8(0x1124)
#define SIGROW_OSC20ERR5V  _SFR_MEM8(0x1125)
#define SIGROW_CHECKSUM1  _SFR_MEM8(0x112F)
```

From iotn3227.h:

```c


/* SYSCFG - System Configuration Registers */
#define SYSCFG_REVID  _SFR_MEM8(0x0F01)


/* NVMCTRL - Non-volatile Memory Controller */
#define NVMCTRL_CTRLA  _SFR_MEM8(0x1000)
#define NVMCTRL_CTRLB  _SFR_MEM8(0x1001)
#define NVMCTRL_STATUS  _SFR_MEM8(0x1002)
#define NVMCTRL_INTCTRL  _SFR_MEM8(0x1003)
#define NVMCTRL_INTFLAGS  _SFR_MEM8(0x1004)
#define NVMCTRL_DATA  _SFR_MEM16(0x1006)
#define NVMCTRL_DATAL  _SFR_MEM8(0x1006)
#define NVMCTRL_DATAH  _SFR_MEM8(0x1007)
#define NVMCTRL_ADDR  _SFR_MEM16(0x1008)
#define NVMCTRL_ADDRL  _SFR_MEM8(0x1008)
#define NVMCTRL_ADDRH  _SFR_MEM8(0x1009)


/* SIGROW - Signature row */
#define SIGROW_DEVICEID0  _SFR_MEM8(0x1100)
#define SIGROW_DEVICEID1  _SFR_MEM8(0x1101)
#define SIGROW_DEVICEID2  _SFR_MEM8(0x1102)
#define SIGROW_SERNUM0  _SFR_MEM8(0x1103)
#define SIGROW_SERNUM1  _SFR_MEM8(0x1104)
#define SIGROW_SERNUM2  _SFR_MEM8(0x1105)
#define SIGROW_SERNUM3  _SFR_MEM8(0x1106)
#define SIGROW_SERNUM4  _SFR_MEM8(0x1107)
#define SIGROW_SERNUM5  _SFR_MEM8(0x1108)
#define SIGROW_SERNUM6  _SFR_MEM8(0x1109)
#define SIGROW_SERNUM7  _SFR_MEM8(0x110A)
#define SIGROW_SERNUM8  _SFR_MEM8(0x110B)
#define SIGROW_SERNUM9  _SFR_MEM8(0x110C)
#define SIGROW_OSCCAL16M0  _SFR_MEM8(0x1118)
#define SIGROW_OSCCAL16M1  _SFR_MEM8(0x1119)
#define SIGROW_OSCCAL20M0  _SFR_MEM8(0x111A)
#define SIGROW_OSCCAL20M1  _SFR_MEM8(0x111B)
```

**Comment by dbuchwald** [comment]
Hold on, what about my changes? Are they still needed?

Sorry, I might have misunderstood, but it seemed to me there were multiple subjects covered here, including new memory type (SIB), and I still haven’t implemented support for it in serialupdi programmer. On top of that, there are still changes in serialupdi.c related to reading chip revision during initialisation. Should it stay there?

Best regards,
Dawid

On 5 Aug 2023, at 10:33, Hans ***@***.******@***.***>> wrote:



@stefanrueger<https://github.com/stefanrueger> I've now resolved the merge conflict, so the PR is now ready.

**Comment by MCUdude** [comment]
@dbuchwald a separate PR that deals wit SIB read has already been merged, and @stefanrueger did the serialupdi implementation, see #1480

**Comment by MCUdude** [comment]
@stefanrueger I suggest we change the size of the IO memory for the megaAVR-0 and tinyAVR-0/1/2 to 0x1100, as the atdf files do. Then we are also able to access the NVM registers as well.

from the megaAVR-0 family datasheet:

image

<br/>
<br/>
<br/>
from the AVR128DA48 datasheet: <br/>
image

**Comment by dbuchwald** [comment]
Thanks for clarification!

Dawid

On 5 Aug 2023, at 10:54, Hans ***@***.******@***.***>> wrote:



@dbuchwald<https://github.com/dbuchwald> a separate PR that deals wit SIB read has already been merged, and @stefanrueger<https://github.com/stefanrueger> did the serialupdi implementation, see #1480<https://github.com/avrdudes/avrdude/pull/1480>

**Comment by stefanrueger** [comment]
> changes in serialupdi.c

@dbuchwald PR #1480 introduced [these changes](https://github.com/avrdudes/avrdude/pull/1480/files#diff-79a97a0f99f34b4d18cc664ce2536146c0821315fdbe772add729526f1087c7b): some overcautious sanity checks, returning OK if a read-only memory is written to with its unchanged content (for a future backup/restore extension of AVRDUDE so that there is no error restoring the existing contents to read-only memories). It turned out that the info needed was already there as you pointed out (thank you). If you feel strongly about formatting/programming style (the PR uses a particularly dense writing style) feel free to put in a PR that adjusts the code to your style.

> change the size of the IO memory for the megaAVR-0 and tinyAVR-0/1/2 [to] access the NVM registers as well

@MCUdude Yes, can do. I would first check whether this creates overlapping memories. These are a nightmare in the `dryrun` programmer b/c whenever the `dryrun` programmer writes to one memory, it needs to update the other memory as well, and the overlaps may be hard to figure out. If the extended `io` doesn't overlap with other NVM memory then OK. The other aspect is documentation in `avrdude.1` and `avrdude.texi`: normally `io` is *volatile* memory, so the doc would say that anything written to these memories will be undefined/lost after reset and that writing may have limited utility for modern AVRs, eg, to test ports I/O. If `io` is a mixture of volatile and non-volatile for some parts, we would need to say so, too.

I will later, in a separate PR, add `io` memories of classic parts; there the `io` memory cannot be programmed externally, only with bootloaders, which has limited use unless the bootloader jumps to the application directly, ie, without a WDT reset.

**Comment by stefanrueger** [comment]
For info, now this PR has the following sizes
| `io` size | No of parts |Parts |
| --: | :-- | :-- |
| 4096 | 50 | ATxmega128A1 ATxmega128A1revD ATxmega128A1U ATxmega128A3 ATxmega128A3U ATxmega128A4 ATxmega128A4 ATxmega128A4U ATxmega128A4U ATxmega128B1 ATxmega128B3 ATxmega128C3 ATxmega128D3 ATxmega128D4 ATxmega16A4 ATxmega16A4 ATxmega16A4 ATxmega16A4 ATxmega16A4U ATxmega16A4U ATxmega16A4U ATxmega16A4U ATxmega16C4 ATxmega16C4 ATxmega16C4 ATxmega16C4 ATxmega16D4 ATxmega16D4 ATxmega16D4 ATxmega16D4 ATxmega16E5 ATxmega16E5 ATxmega16E5 ATxmega16E5 ATxmega192A1 ATxmega192A3 ATxmega192A3U ATxmega192C3 ATxmega192D3 ATxmega256A1 ATxmega256A1 ATxmega256A3 ATxmega256A3 ATxmega256A3B ATxmega256A3B ATxmega256A3BU ATxmega256A3BU ATxmega256A3U ATxmega256A3U ATxmega256C3 ATxmega256C3 ATxmega256D3 ATxmega256D3 ATxmega32A4 ATxmega32A4 ATxmega32A4 ATxmega32A4 ATxmega32A4U ATxmega32A4U ATxmega32A4U ATxmega32A4U ATxmega32C3 ATxmega32C3 ATxmega32C3 ATxmega32C3 ATxmega32C4 ATxmega32C4 ATxmega32C4 ATxmega32C4 ATxmega32D3 ATxmega32D3 ATxmega32D3 ATxmega32D3 ATxmega32D4 ATxmega32D4 ATxmega32D4 ATxmega32D4 ATxmega32E5 ATxmega32E5 ATxmega32E5 ATxmega32E5 ATxmega384C3 ATxmega384C3 ATxmega384D3 ATxmega384D3 ATxmega64A1 ATxmega64A1 ATxmega64A1 ATxmega64A1 ATxmega64A1U ATxmega64A1U ATxmega64A1U ATxmega64A1U ATxmega64A3 ATxmega64A3 ATxmega64A3 ATxmega64A3 ATxmega64A3U ATxmega64A3U ATxmega64A3U ATxmega64A3U ATxmega64A4 ATxmega64A4 ATxmega64A4 ATxmega64A4 ATxmega64A4U ATxmega64A4U ATxmega64A4U ATxmega64A4U ATxmega64B1 ATxmega64B1 ATxmega64B1 ATxmega64B1 ATxmega64B3 ATxmega64B3 ATxmega64B3 ATxmega64B3 ATxmega64C3 ATxmega64C3 ATxmega64C3 ATxmega64C3 ATxmega64D3 ATxmega64D3 ATxmega64D3 ATxmega64D3 ATxmega64D4 ATxmega64D4 ATxmega64D4 ATxmega64D4 ATxmega8E5 |
|4160|45 |AVR128DA28 AVR128DA32 AVR128DA48 AVR128DA64 AVR128DB28 AVR128DB32 AVR128DB48 AVR128DB64 AVR16DD14 AVR16DD20 AVR16DD28 AVR16DD32 AVR16EA28 AVR16EA32 AVR16EA48 AVR32DA28 AVR32DA32 AVR32DA48 AVR32DB28 AVR32DB32 AVR32DB48 AVR32DD14 AVR32DD20 AVR32DD28 AVR32DD32 AVR32EA28 AVR32EA32 AVR32EA48 AVR64DA28 AVR64DA32 AVR64DA48 AVR64DA64 AVR64DB28 AVR64DB32 AVR64DB48 AVR64DB64 AVR64DD14 AVR64DD20 AVR64DD28 AVR64DD32 AVR64EA28 AVR64EA32 AVR64EA48 AVR8EA28 AVR8EA32|
|4352 | 46 |ATmega1608 ATmega1609 ATmega3208 ATmega3209 ATmega4808 ATmega4809 ATmega808 ATmega809 ATtiny1604 ATtiny1606 ATtiny1607 ATtiny1614 ATtiny1616 ATtiny1617 ATtiny1624 ATtiny1626 ATtiny1627 ATtiny202 ATtiny204 ATtiny212 ATtiny214 ATtiny3216 ATtiny3217 ATtiny3224 ATtiny3226 ATtiny3227 ATtiny402 ATtiny404 ATtiny406 ATtiny412 ATtiny414 ATtiny416 ATtiny416auto ATtiny417 ATtiny424 ATtiny426 ATtiny427 ATtiny804 ATtiny806 ATtiny807 ATtiny814 ATtiny816 ATtiny817 ATtiny824 ATtiny826 ATtiny827|

**Comment by stefanrueger** [comment]
@MCUdude Having looked closer at the `io` datasheet definitions I would **not** extend the `io` to stretch to the NVM controller and (some) NVM memories. This to avoid overlapping memories in the memory layout. So far, we only have two cases where memories overlap: flash memories in XMEGAs (apptable, application, boot and flash) and the general `fuses` memory (10 bytes) and the `fuse`$n$ individual bytes, $n\in\{0, ... 9\}$. The latter has been considered in the dryrun programmer, the former have not (yet) but should. It is better to not create more memories with overlaps.

**Comment by MCUdude** [comment]
> I would not extend the io to stretch to the NVM controller and (some) NVM memories

This means that the IO memory size can't be larger than 0x1000 bytes on megaAVR0, tinyAVR0/1/2, and AVR-Dx/Ex. Do you want me to update the PR where I change the size to 0x1000?

**Comment by stefanrueger** [comment]
> update the PR where I change the size

Yes, I think this is how it was before. Your first analysis was right, the .atdf are wrong as they cover more than the volatile memories.

**Comment by stefanrueger** [comment]
@MCUdude If you are happy and have finished testing I can merge

**Comment by MCUdude** [comment]
if we extend `io` to 0x1100 (all except for XMEGA) there still won't be an overlap in avrdude.conf? AFAIK Avrdude doesn't utilize he NVM controller

**Comment by stefanrueger** [comment]
> extend io to 0x1100 

Your call. Please just make sure `io` won't overlap with any other memory in avrdude.conf (e, lock bits, fuses, eeprom, ...)

**Comment by MCUdude** [comment]
> Please just make sure io won't overlap with any other memory in avrdude.conf (eg, lock bits, fuses, eeprom, ...)

I'll double-check that this won't lead to any overlap what so ever.

**Comment by MCUdude** [comment]
I've rolled back the last commit, so now the IO memory correlates with the ATDF files (well, except for the 0x103F/0x1040 typo). The registers for the NVM controller (which I'm pretty sure are volatile) are now included in the IO memory,

I'm fine with merging this PR. Too bad I couldn't figure out how to write to the Xmega IO registers...
