### PR TITLE
fix erasing of locked devices with pickit5 programmer. Fix for #2049

### LINKED ISSUE #2049: Pickit5 HVUPDI seems unable to unlock devices
Using AVRDUDE 8.1 (avrdude-v8.1-windows-mingw-x64) I am attempting to communicate with an ATTINY device that has the lock fuse set requiring the high voltage pulse on the UPDI/Reset pin to unlock.

The following command works perfectly with a Pickit4:
avrdude -c pickit4_updi -p attiny412 -x hvupdi -B 125khz -vv

However the following does not
avrdude -c pickit5_updi -p attiny412 -x hvupdi -B 125khz -vv

With this returning the following output:

```
Using port            : usb
Using programmer      : pickit5_updi
Setting bit clk period: 8.0 us
Usbdev_open(): found MPLAB? PICkit 5, serno: 020026702RYN012839
AVR part              : ATtiny412
Programming modes     : SPM, UPDI

Memory           Size  Pg size  Offset
--------------------------------------
eeprom            128       32  0x1400
flash            4096       64  0x8000
fuses              10        1  0x1280
fuse0/wdtcfg        1        1  0x1280
fuse1/bodcfg        1        1  0x1281
fuse2/osccfg        1        1  0x1282
fuse4/tcd0cfg       1        1  0x1284
fuse5/syscfg0       1        1  0x1285
fuse6/syscfg1       1        1  0x1286
fuse7/append        1        1  0x1287
fuse8/bootend       1        1  0x1288
lock                1        1  0x128a
prodsig/sigrow     64       64  0x1100
signature           3        1  0x1100
sernum             10        1  0x1103
osccal16            2        1  0x1118
osccal20            2        1  0x111a
tempsense           2        1  0x1120
osc16err            2        1  0x1122
osc20err            2        1  0x1124
userrow/usersig    32       32  0x1300
io               4352        1       0
sram              256        1  0x3f00
sib                32        1       0

Variants        Package  F max   T range         V range
---------------------------------------------------------------
ATtiny412-SSF   SOIC8    20 MHz  [-40 C, 125 C]  [1.8 V, 5.5 V]
ATtiny412-SSFR  SOIC8    20 MHz  [-40 C, 125 C]  [1.8 V, 5.5 V]
ATtiny412-SSN   SOIC8    20 MHz  [-40 C, 105 C]  [1.8 V, 5.5 V]
ATtiny412-SSNR  SOIC8    20 MHz  [-40 C, 105 C]  [1.8 V, 5.5 V]

Programmer type       : pickit5
Description           : MPLAB(R) PICkit 5 in UPDI mode
Application version   : 02.01.38
Serial number         : 020026702RYN012839
High-voltage SYSCFG0 override on UPDI pin enabled
Target Vdd: 5.16 V, target current: 0 mA
External voltage detected: will not supply power
Error pickit5_read_response() pickit5.c 406: script error returned: 0x44
Error pickit5_send_script_cmd() pickit5.c 483: reading script response failed
Error main() main.c 1632: initialization failed  (rc = -1)
 - double check the connections and try again
 - use -B to set lower the bit clock frequency, e.g. -B 125kHz
 - reset the programmer by unplugging it
 - use -F to override this check

Avrdude done.  Thank you.
```

Any thoughts? Is this functionality not fully implemented for the Pickit5 yet?

### PR DESCRIPTION
**Pull request by MX682X**
should fix #2049 
UPDI seems to be doing fine, going to test other protocols soon.

Also pulling in updated Toolpacks
Also Also: new Device Family found: LA-Family (shares scripts with EB series, so pretty similar to those probably)

### CODE REVIEW

**Comment by stefanrueger** [comment]
> extend the LIBAVRDUDE error codes with LIBAVRDUDE_DEVICE_LOCKED

Sounds like a good course if action

File: src/pickit5.c [hunk 1]
```diff
@@ -92,7 +93,8 @@ struct pdata {
 
   unsigned char nvm_version;    // Used to determine the offset for SIGROW/DevID on UPDI
 
-  unsigned char dW_switched_isp; // for debugWIRE: Flag to indicate we switch to ISP
+  unsigned char dW_switched_isp;  // for debugWIRE: Flag to indicate we switch to ISP
+  unsigned char target_locked;    // avoid additional "program_enable" when doing chip erase
```
Comment (stefanrueger) [inline src/pickit5.c:97]: Same here

File: src/pickit5.c [hunk 2]
```diff
@@ -212,6 +215,65 @@ static int usbdev_bulk_send(const union filedescriptor *fd, const unsigned char
 // Check if the device exists
 static int usbdev_check_connected(unsigned int vid, unsigned int pid);
 
+const char * pickit5_error_to_str(unsigned int error_code) {
+  if      (error_code == 0)  { return "NO_ERROR" ;}   // This strings were found in the depths of the IDE files (HEX Editor ftw!)
```
Comment (stefanrueger) [inline src/pickit5.c:219]: This is not wrong but
  - Lots of elsing returns
  - Too many `if`s; better use `switch` (compiler makes decision tree with fewer (ca $log2(n)$)` branches as opposed to $n$ successive `if`s in worst case

Crisper and cleaner:

```
  switch(error_code) {          // These strings were found in the depths of the IDE files (HEX Editor ftw!)
  case   0: return "NO_ERROR";
  case  16: return "DW_PHY_ERROR";
  case  17: return "JTAGM_INIT_ERROR";
  case  18: return "JTAGM_ERROR";
  case  19: return "JTAG_ERROR";
  case  20: return "JTAGM_VERSION";
  case  21: return "JTAGM_TIMEOUT";
  case  22: return "JTAG_BIT_BANGER_TIMEOUT";
  case  23: return "PARITY_ERROR";
  case  24: return "EB_ERROR";
  case  25: return "PDI_TIMEOUT";
  case  26: return "COLLISION";
  case  27: return "PDI_ENABLE";
  case  28: return "FRAMING_ERROR";
  case  29: return "DMA_ERROR";
  case  32: return "NO_DEVICE_FOUND";
  case  33: return "CLOCK_ERROR";
  case  34: return "NO_TARGET_POWER";
  case  35: return "NOT_ATTACHED";
  case  36: return "DAISY_CHAIN_TOO_LONG";
  case  37: return "DAISY_CHAIN_CONFIG";
  case  49: return "INVALID_PHYSICAL_STATE";
  case  50: return "ILLEGAL_STATE";
  case  51: return "INVALID_CONFIG";
  case  52: return "INVALID_MEMTYPE";
  case  53: return "INVALID_SIZE";
  case  54: return "INVALID_ADDRESS";
  case  55: return "INVALID_ALIGNMENT";
  case  56: return "ILLEGAL_MEMORY_RANGE";
  case  57: return "ILLEGAL_VALUE";
  case  58: return "ILLEGAL_ID";
  case  59: return "INVALID_CLOCK_SPEED";
  case  60: return "TIMEOUT";
  case  61: return "ILLEGAL_OCD_STATUS";
  case  64: return "NVM_ENABLE";
  case  65: return "NVM_DISABLE";
  case  66: return "CS_ERROR";
  case  67: return "CRC_FAILURE";
  case  68: return "OCD_LOCKED";
  case  69: return "KEY_ERROR";
  case  70: return "BOOT_ERROR";
  case  71: return "ACK_ERROR";
  case  80: return "NO_OCD_CONTROL";
  // case 81: return "PLEASE_TOGGLE_POWER";  // Original, but the one below might help better
  case  81: return "NO_RESPONSE_CHECK_CONNECTIONS";
  case  82: return "NO_VOUT_SET";
  case  83: return "VOUT_ERROR";
  case  84: return "VTG_TOO_LOW_FOR_FEATURE";
  case  96: return "PC_READ_FAILED";
  case  97: return "REGISTER_READ_FAILED";
  case 112: return "READ_ERROR";
  case 113: return "WRITE_ERROR";
  case 114: return "WRITE_TIMEOUT";
  case 144: return "NOT_SUPPORTED";
  case 145: return "NOT_IMPLEMENTED";
  default:  return "UNKNOWN";
  }
```

File: src/pickit5.c [hunk 3]
```diff
@@ -402,12 +461,22 @@ static int pickit5_read_response(const PROGRAMMER *pgm) {
     return ERROR_BAD_RESPONSE;
   }
 
-  if(error_code != 0x00) {
-    pmsg_error("script error returned: 0x%2X\n", error_code);
+  if(error_code == 0x44) {
+    my.target_locked = 0x01;
```
Comment (stefanrueger) [inline src/pickit5.c:465]: Why not `my.target_locked = 1;`? Seems to be used as Boolean.

File: src/pickit5.c [hunk 4]
```diff
@@ -402,12 +461,22 @@ static int pickit5_read_response(const PROGRAMMER *pgm) {
...
+    return LIBAVRDUDE_DEVICE_LOCKED;
+  } else if (error_code == 0x51) {
+    if(is_updi(pgm)) {
+      pmsg_error("Failed to start session. Reason might be: no power, bad connection or missing HV pulse.");
+    } else {
+      pmsg_error("Failed to start session. Reason might be: no power or bad connection");
+    }
+    return LIBAVRDUDE_GENERAL_FAILURE;
+  } else if(error_code != 0x00) {
```
Comment (stefanrueger) [inline src/pickit5.c:474]: Please don't `else` a `return`.

File: src/pickit5.c [hunk 5]
```diff
@@ -402,12 +461,22 @@ static int pickit5_read_response(const PROGRAMMER *pgm) {
...
-  if(error_code != 0x00) {
-    pmsg_error("script error returned: 0x%2X\n", error_code);
+  if(error_code == 0x44) {
+    my.target_locked = 0x01;
+    return LIBAVRDUDE_DEVICE_LOCKED;
+  } else if (error_code == 0x51) {
+    if(is_updi(pgm)) {
+      pmsg_error("Failed to start session. Reason might be: no power, bad connection or missing HV pulse.");
+    } else {
+      pmsg_error("Failed to start session. Reason might be: no power or bad connection");
```
[the remark this answers is not in the document]
Comment (stefanrueger) [reply src/pickit5.c:471]: Also AVRDUDE rarely does full sentences in error messages. Better use ` session; reason`

**Comment by MX682X** [comment]
I decided to thow in a python script for linting. Should help in the future. Can be expanded in the future

**Comment by stefanrueger** [comment]
@MX682X Looks great!

@MCUdude @TJALambert could you please try this PR out and confirm it solves the problem, so the PR can be merged

**Comment by TJALambert** [comment]
Just tested it.
My original command of: `avrdude -c pickit5_updi -p attiny412 -x hvupdi -B 125khz -vv`
Ultimately returned 
```
...
Error pickit5_send_script_cmd() pickit5.c 554: reading script response failed
Error main() main.c 1633: initialisation failed: device is locked; chip erase required to unlock

Avrdude done.  Thank you.
```

Running command: `avrdude -c pickit5_updi -p attiny412 -x hvupdi -B 125khz -vv -e`
Successfully erased the target as expected.

Will play around with it some more when I get more time but for now it looks good, many thanks.

**Comment by MX682X** [comment]
Seen the message, but I don't know when I will be able to implement the ideas

**Comment by MX682X** [comment]
Locking the device and forcing usage of HVUPDI:
```
./build_linux/src/avrdude -c pickit5_updi -pt1614 -xvtarg=3.3 -xhvupdi -Usyscfg0:w:0xc1:m -Ulock:w:0x00:m

Processing -U syscfg0:w:0xc1:m
Reading 1 byte for fuse5/syscfg0 from input file 0xc1
Writing 1 byte (0xC1) to fuse5/syscfg0, 1 byte written, 1 verified

Processing -U lock:w:0x00:m
Reading 1 byte for lock from input file 0x00
Writing 1 byte (0x00) to lock, 1 byte written, 1 verified

Avrdude done.  Thank you.
```

```
./build_linux/src/avrdude -c pickit5_updi -pt1614 -xvtarg=3.3 -xhvupdi && echo OK || echo Error
Warning: device locked; any operation will require chip erase option -e

Avrdude done.  Thank you.
OK

```

```
./build_linux/src/avrdude -c pickit5_updi -pt1614 -xvtarg=3.3 -xhvupdi -Ueeprom:r:/dev/null && echo OK || echo Error
Error: device locked; chip erase option -e required for unlocking device first

Avrdude done.  Thank you.
Error
```

```
./build_linux/src/avrdude -c pickit5_updi -pt1614 -xvtarg=3.3 -xhvupdi -e -Ueeprom:r:/dev/null && echo OK || echo Error
Target successfully erased
Target successfully erased
Reading eeprom memory ...
Reading | ################################################## | 100% 0.03 s 
Writing 256 bytes to output file /dev/null

Avrdude done.  Thank you.
OK
```

Currently, the Target is erased twice, otherwise worked as expected

**Comment by MX682X** [comment]
Now: 
```
./build_linux/src/avrdude -c pickit5_updi -pt1614 -xvtarg=3.3 -xhvupdi -Usyscfg0:w:0xc1:m -Ulock:w:0x00:m
```

```
./build_linux/src/avrdude -c pickit5_updi -pt1614 -xvtarg=3.3 -xhvupdi -e -Ueeprom:r:/dev/null && echo OK || echo Error
Target successfully erased
Reading eeprom memory ...
Reading | ################################################## | 100% 0.03 s 
Writing 256 bytes to output file /dev/null

Avrdude done.  Thank you.
OK
```

**Comment by stefanrueger** [comment]
@MX682X Thanks for the tests and the guard against double erasing. Looks like this is ready to merge (will do within a couple of weeks).
